include ':app', ':automator', ':bot', ':common', ':autojs', ':inrt', ':apkbuilder'
project(':autojs').projectDir = file('autotools')
include ':LocalRepo:libtermexec'
include ':LocalRepo:emulatorview'
include ':LocalRepo:term'
include ':LocalRepo:p7zip'
include ':LocalRepo:OpenCV'
include ':paddleocr'
